export const projects = [
  {
    slug: "codeanew-platform",
    category: "Web Development",
    client: "codeanew",
    title: "codeanew Company Website",
    short: "A full company website built for a UAE-based software agency — designed to convert visitors into leads.",
    thumbnail: "/projects/codeanew.jpg",
    tags: ["React", "Node.js", "Tailwind CSS"],
    overview: "codeanew needed a professional web presence that reflected their positioning as a long-term technology partner for UAE businesses. The goal was a fast, modern website that clearly communicated services and drove booking calls.",
    problem: "Most agency websites either look like generic templates or try to impress with complexity. codeanew needed something that felt confident, honest, and built for conversion — not just aesthetics.",
    solution: "We built a React-based single page application with a component-driven architecture, Cal.com booking integration, HubSpot chat, and a fully responsive design system built on Tailwind CSS and custom design tokens.",
    result: "A production-ready website with clean code, fast load times, and a clear conversion path from hero to booking call.",
    technologies: ["React", "Tailwind CSS", "Node.js", "Cal.com", "HubSpot", "Formik", "Axios"],
    year: "2024",
    industry: "Technology",
  },
  {
    slug: "custom-crm-uae",
    category: "CRM Development",
    client: "Confidential — Trading Company",
    title: "Custom CRM for UAE Trading Company",
    short: "A fully custom CRM built to replace a patchwork of Excel sheets and WhatsApp groups for a growing UAE trading business.",
    thumbnail: "/projects/crm.jpg",
    tags: ["React", "Laravel", "MySQL"],
    overview: "A UAE-based trading company was managing their entire sales pipeline through Excel, WhatsApp, and memory. As the team grew, deals were being lost and follow-ups were missed.",
    problem: "Off-the-shelf CRMs like Salesforce and HubSpot were either too expensive, too complex, or didn't support their Arabic-language workflow. They needed something built around how they actually work.",
    solution: "We built a fully custom CRM with lead tracking, sales pipeline visualization, task automation, Arabic and English support, role-based access for the sales team, and a mobile-friendly interface for field reps.",
    result: "The sales team reduced missed follow-ups by over 70% in the first month. Management gained full visibility into the pipeline for the first time.",
    technologies: ["React", "Laravel", "MySQL", "Redis", "AWS"],
    year: "2024",
    industry: "Trading & Distribution",
  },
];
