name: Sync Branches

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the 'main' branch

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge 'main' into other branches
        run: |
          branches=("dev" "backend/api" "frontend/admin" "frontend/public")

          for branch in "${branches[@]}"; do
            git fetch origin
            git checkout $branch
            git merge origin/main --allow-unrelated-histories --no-ff -m "Merge main into $branch"
            git push origin $branch
          done

